### ISSUE TITLE
[DRAFT] Implement `configOnly` mode for virtual endpoint

### ISSUE THREAD

**Issue by chanwit** [weave-ai/weave-ai#12]
For example:

```yaml
spec:
  sourceRef:
    kind: Secret
    name: gpt-4-config
    namespace: weave-ai
  engine: None
```

In Secret `gpt-4-config`, we would expect configurations required for OpenAI.
```yaml
TBD
```

**Comment by chanwit** [comment]
`ExternalLanguageModel`

or 

```yaml
spec:
  mode: ClusterLM # ExternalLM
external:
  endpoint: https://...
  secretRef:
    name: gpt-4-config
```
